#!/bin/bash
#

echo "==================STARTING BUILD=================="
pushd ../build/build_simd &> /dev/null
g++ -Wextra -g -march=native -Og -o raytracing_simd ../../code/simd_version/raytracing_simd.cpp -lm
popd &> /dev/null
echo "==================BUILD FINISHED=================="